package dbtypes

const (
	PgSmallint                 = "smallint"
	PgInteger                  = "integer"
	PgBigint                   = "bigint"
	PgCharacterVarying         = "character varying"
	PgVarchar                  = "varchar"
	PgText                     = "text"
	PgReal                     = "real"
	PgDoublePrecision          = "double precision"
	PgTimestamp                = "timestamp"
	PgTimestampWithTimeZone    = "timestamp with time zone"
	PgTimestampWithoutTimeZone = "timestamp without time zone"
	PgDate                     = "date"
	PgTime                     = "time"
	PgTimeWithoutTimeZone      = "time without time zone"
	PgTimeWithTimeZone         = "time with time zone"
	PgInterval                 = "interval"
	PgBoolean                  = "boolean"
	PgDecimal                  = "decimal"
	PgNumeric                  = "numeric"
	PgCharacter                = "character"
	PgChar                     = "char"
	PgJsonb                    = "jsonb"
	PgJson                     = "json"
	PgUuid                     = "uuid"
	PgBytea                    = "bytea"
	PgInet                     = "inet"

	//adjust specific
	PgAdjustIstore     = "istore"
	PgAdjustBigIstore  = "bigistore"
	PgAdjustAjBool     = "ajbool"
	PgAdjustAjTime     = "ajtime"
	PgAdjustAjDate     = "ajdate"
	PgAdjustCountry    = "country"
	PgAdjustDeviceType = "device_type"
	PgAdjustOsName     = "os_name"
)
