package utils

const (
	ChInt8        = "Int8"
	ChInt16       = "Int16"
	ChInt32       = "Int32"
	ChInt64       = "Int64"
	ChUInt8       = "UInt8"
	ChUInt16      = "UInt16"
	ChUint32      = "UInt32"
	ChUint64      = "UInt64"
	ChFloat32     = "Float32"
	ChFloat64     = "Float64"
	ChFixedString = "FixedString"
	ChString      = "String"
	ChDate        = "Date"
	ChDateTime    = "DateTime"
	ChDecimal     = "Decimal"
	ChUUID        = "UUID"
	ChUInt8Array  = "Array(UInt8)"

	PgSmallint                 = "smallint"
	PgInteger                  = "integer"
	PgBigint                   = "bigint"
	PgCharacterVarying         = "character varying"
	PgVarchar                  = "varchar"
	PgText                     = "text"
	PgReal                     = "real"
	PgDoublePrecision          = "double precision"
	PgTimestamp                = "timestamp"
	PgTimestampWithTimeZone    = "timestamp with time zone"
	PgTimestampWithoutTimeZone = "timestamp without time zone"
	PgDate                     = "date"
	PgTime                     = "time"
	PgTimeWithoutTimeZone      = "time without time zone"
	PgTimeWithTimeZone         = "time with time zone"
	PgInterval                 = "interval"
	PgBoolean                  = "boolean"
	PgDecimal                  = "decimal"
	PgNumeric                  = "numeric"
	PgCharacter                = "character"
	PgChar                     = "char"
	PgJsonb                    = "jsonb"
	PgJson                     = "json"
	PgUuid                     = "uuid"
	PgBytea                    = "bytea"
	PgInet                     = "inet"
)
